version: '3.7'

services:
  db:
    image: mysql
    restart: always
    volumes:
      - ./dbinit/init.sql:/dbinit/init.sql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    container_name: db
    ports:
      - '9906:3306'
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - 8080:8080